"""document tags table

Revision ID: f080582d2f7d
Revises: 65c508e48a47
Create Date: 2022-05-06 18:44:13.661468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f080582d2f7d'
down_revision = '65c508e48a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_text', sa.String(length=200), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('document', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_document_timestamp'), 'document', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_timestamp'), table_name='document')
    op.drop_column('document', 'timestamp')
    op.drop_table('document_tag')
    # ### end Alembic commands ###
